### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by czainab** [deeplizard/Keras-Machine-Learning-Deep-Learning-Tutorial#4]
Hi @deeplizard, I am learning to apply keras and found your video tutorials very helpful. I want to ask that, can I predict the class labels of certain images which are not in the labeled folders e.g can I put all the test images of cats and dogs in a single folder and predict?
I tried this with your code 
predictions = model.predict_generator(test_batches, steps=1, verbose=0)
But it was giving an error of dividing by zero and when I organize the test images under labeled folders the error was gone. So can you please tell me the code to predict image labels when they are just dumped into a folder.

**Comment by deeplizard** [comment]
Hey @czainab,

If you don't know the labels for the test data, you need to have one more directory within the "test" folder. Call the nested directory "unknown" for example. Then, within this unknown folder, place all the unlabeled test images there. 

With this structure, you will need to modify the `test_batches` variable. The parameters called `classes` and `class_mode` within this variable will need to be changed. Specifically, the change will be to make `classes = None` and `class_mode = None`. This is due to not knowing the labels for the test data.

**Comment by czainab** [comment]
Thank you got it :)
